syncMode = sharedDir

[serverClass:aws]
whitelist.0 = 403041fa-6e9a-547c-ab1c-286e4151223d

[serverClass:azure]
whitelist.0 = 8767683d-eed8-5882-be84-b07e1e5a3a3f

[serverClass:gcp]
whitelist.0 = b868070b-5334-5c89-971e-3e5b27d2b9e4

[serverClass:aws:app:Splunk_TA_aws]

[serverClass:azure:app:Splunk_TA_microsoft-cloudservices]

[serverClass:gcp:app:Splunk_TA_google-cloudplatform]
