services:
  enterprise:
    build:
      context: enterprise
    ports:
      - 8000:8000
    volumes:
      # Mounting docker.sock is required to query docker API from within the container.
      - /var/run/docker.sock:/var/run/docker.sock

  universal_forwarder:
    tty: true
    build:
      context: universal-forwarder
    volumes:
      # Mounting docker.sock is required to query docker API from within the container.
      - /var/run/docker.sock:/var/run/docker.sock
