name: leader_follower

services:
  deployment_server_leader:
    ports:
      - 8000:8000
    build:
      context: leader
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1s
      timeout: 1s
      retries: 60

  deployment_server_usa:
    ports:
      - 8001:8000
    build:
      context: follower
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1s
      timeout: 1s
      retries: 60
    depends_on:
      deployment_server_leader:
        condition: service_healthy

  universal_forwarder_usa:
    tty: true
    hostname: usa
    build:
      context: universal-forwarder
      args:
        SPLUNK_FORWARDER_CONFIGURATION_PATH: etc/usa
    depends_on:
      deployment_server_usa:
        condition: service_healthy
    deploy:
      replicas: 2

  deployment_server_europe:
    ports:
      - 8002:8000
    build:
      context: follower
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1s
      timeout: 1s
      retries: 60
    depends_on:
      deployment_server_leader:
        condition: service_healthy

  universal_forwarder_europe:
    tty: true
    hostname: usa
    build:
      context: universal-forwarder
      args:
        SPLUNK_FORWARDER_CONFIGURATION_PATH: etc/europe
    depends_on:
      deployment_server_europe:
        condition: service_healthy
    deploy:
      replicas: 2
