name: standalone

services:
  deployment_server:
    build:
      context: enterprise
      secrets:
        - splunkbase_username
        - splunkbase_password
    ports:
      - 8000:8000
    volumes:
      # Mounting docker.sock is required to query docker API from within the container.
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1s
      timeout: 1s
      retries: 30

  universal_forwarder:
    tty: true
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      deployment_server:
        condition: service_healthy
    build:
      context: universal-forwarder
    volumes:
      # Mounting docker.sock is required to query docker API from within the container.
      - /var/run/docker.sock:/var/run/docker.sock

secrets:
  splunkbase_username:
    file: secrets/splunkbase_username.txt
  splunkbase_password:
    file: secrets/splunkbase_password.txt
