name: cluster

services:
  traefik:
    image: traefik:v3.3.6
    ports:
      - 3000:80
    volumes:
      - ./traefik/dynamic.yaml:/etc/traefik/dynamic.yaml
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml

  docker_socket_proxy:
    environment:
      CONTAINERS: 1
    image: tecnativa/docker-socket-proxy:0.3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  deployment_server_europe:
    build:
      context: enterprise
      args:
        SPLUNK_CONFIGURATION_PATH: deployment-server-europe/etc
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ./deployment_apps:/opt/splunk/etc/deployment-apps
      - ./client_events:/opt/splunk/var/log/client_events

  universal_forwarder_europe:
    tty: true
    hostname: europe
    deploy:
      replicas: 2
    depends_on:
      deployment_server_europe:
        condition: service_healthy
    build:
      context: universal-forwarder
      args:
        SPLUNK_FORWARDER_CONFIGURATION_PATH: etc/europe

  deployment_server_usa:
    build:
      context: enterprise
      args:
        SPLUNK_CONFIGURATION_PATH: deployment-server-usa/etc
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ./deployment_apps:/opt/splunk/etc/deployment-apps
      - ./client_events:/opt/splunk/var/log/client_events

  universal_forwarder_usa:
    tty: true
    hostname: usa
    deploy:
      replicas: 2
    depends_on:
      deployment_server_usa:
        condition: service_healthy
    build:
      context: universal-forwarder
      args:
        SPLUNK_FORWARDER_CONFIGURATION_PATH: etc/usa

  whoami_1:
    image: traefik/whoami:v1.11

  whoami_2:
    image: traefik/whoami:v1.11
