[default]
syncMode = sharedDir

[serverClass:usa]
whitelist.0 = usa

[serverClass:usa:app:Splunk_TA_google-cloudplatform]

[serverClass:all]
whitelist.0 = *

[serverClass:all:app:Splunk_TA_microsoft-cloudservices]
