[serverClass:follower_deployment_apps]
restartSplunkWeb = 0
restartSplunkd = 0
stateOnClient = noop
targetRepositoryLocation = $SPLUNK_HOME/etc/deployment-apps
whitelist.0 = *

[serverClass:follower_deployment_apps:app:universal_forwarder_configuration]

[serverClass:follower_configuration_apps]
restartSplunkWeb = 0
restartSplunkd = 0
stateOnClient = noop
targetRepositoryLocation = $SPLUNK_HOME/etc/apps
whitelist.0 = *

[serverClass:follower_configuration_apps:app:follower_configuration]
