[serverClass:aws]
whitelist.0 = a7038c37-a0a6-529b-9e01-c1481a9fe67e

[serverClass:azure]
whitelist.0 = e5fb2b42-d7a2-5679-86ed-36037a1a51d2

[serverClass:gcp]
whitelist.0 = aa724fff-dfd1-55a7-9687-bb9684704501

[serverClass:all]
whitelist.0 = *

[serverClass:aws:app:Splunk_TA_aws]

[serverClass:azure:app:Splunk_TA_microsoft-cloudservices]

[serverClass:gcp:app:Splunk_TA_google-cloudplatform]

[serverClass:all:app:SA-Eventgen]
